### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by rogerjaffe** [chrokh/snake#4]
When running node cli I'm getting a syntax error on line 21 with the trailing comma.  Removing the comma fixes the syntax error and the program runs normally.

**Comment by chrokh** [comment]
Thanks for the ping! Hmm..

1) What version of node are you running?
```bash
$ node -v
v10.8.0
```

2) Could you please post the syntax error.

**Comment by rogerjaffe** [comment]
Here's a screenshot:

[image: Screen Shot 2018-08-11 at 4.29.19 AM.png]

**Comment by chrokh** [comment]
It seems the image didn't get attached. Perhaps just copy-paste the error message? Trying to figure out how to reproduce the error :)

**Comment by huymai1** [comment]
Hi

**Comment by rogerjaffe** [comment]
Hi -- sorry... I was out of town this weekend.  Here's a link to the
screenshot:

https://drive.google.com/file/d/1zfPYCe1l3-5e94DjTqmU7iMMB6psGbUs/view?usp=sharing

**Comment by chrokh** [comment]
Thanks for supplying the screenshot.

This is an issue with older versions of Node.js. Trailing commas in object literals seems to have been [legal since ECMAScript 5](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas).

I happened to have Node.js `7.7.1` installed and I get the same error when running this script with that version. I.e.:

```bash
$ n 7.7.1
$ node cli
/Users/chris/code/work/snake/cli.js:22
  )(state)
  ^
SyntaxError: Unexpected token )
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
```

Apologies for not thinking of testing with an older version myself first :)

If you install a newer version of Node.js it will run fine. If you're not already using a version manager for Node.js I'd recommend ["n"](https://github.com/tj/n).

**Comment by rogerjaffe** [comment]
Thank you for following up.  After I sent you the first email I thought
that it may be a Node version problem but haven't had a chance to check
it.  Now I know!!

RJ
